# Use the official Node.js image as the base image
FROM node:18

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy only app.js and db.js
COPY *.js ./

# Expose the port the app runs on
EXPOSE 8000

# Start the application
CMD ["npm", "start"]
